[theme]
primaryColor="#667eea"
backgroundColor="#f5f7fa"
secondaryBackgroundColor="#ffffff"
textColor="#1f2937"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=true
headless=true
port=8501
